package main

import (
	"fmt"
)

func main() {
	scores := make([]int, 0, 10)
	scores = append(scores, 5)
	scores = append(scores, 11111111111)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	scores = append(scores, 11)
	//I writed all of this because I wanted to see an out of range error
	fmt.Println(scores)
}
